split_things = {
    '(': 'parenthesis',
    ')': 'parenthesis',
    '{': 'curly_bracket',
    '}': 'curly_bracket',
    ';': 'semicolon',
    ',': 'comma',
    ' ': 'space',
    '\n': 'newline',
    '\t': 'tab',
    '!': 'exclamation',
    '<': 'less_than',
    '>': 'greater_than',
    '=': 'equal',
    '+': 'plus',
    '-': 'minus',
    '*': 'asterisk',
    '/': 'slash',
    '%': 'percent',
    '&': 'ampersand',
    '|': 'pipe',
    '^': 'caret',
    '~': 'tilde',
    '[': 'square_bracket',
    ']': 'square_bracket',
    '?': 'question_mark',
    ':': 'colon',
    '"': 'double_quote',
    '\'': 'single_quote',
    '\\': 'backslash',
    '#': 'hash',
    '.': 'dot'
}